name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: withastro/action@v2
        with:
          path: .
          node-version: 20